// README Generator — §4.8 of the implementation plan.

import type { NormalizedSubmission, AnalyticsSnapshot } from "../adapters/types";

// Escape markdown-breaking characters from scraped strings.
export function escapeMd(input: string): string {
  return input
    .replace(/[\\`*_{}[\]()#+\-.!|~>]/g, "\\$&")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Build the URL to the original problem on the platform.
function problemUrl(s: NormalizedSubmission): string {
  switch (s.platform) {
    case "leetcode":
      return `https://leetcode.com/problems/${encodeURIComponent(s.slug)}/`;
    case "codeforces":
      return `https://codeforces.com/problemset/problem/${encodeURIComponent(s.problemId)}`;
    case "codechef":
      return `https://www.codechef.com/problems/${encodeURIComponent(s.slug)}`;
    default:
      return "#";
  }
}

// Merge the existing solution list with a new language entry.
function mergeSolutionList(
  existingFiles: string[] | null,
  newLanguage: string
): string[] {
  const langs = new Set<string>();

  if (existingFiles) {
    for (const file of existingFiles) {
      if (file.startsWith("solution")) {
        // Extract extension
        const ext = file.split(".").pop() ?? "";
        if (ext && ext !== "md") {
          langs.add(ext);
        }
      }
    }
  }

  // Map extension back to language name for display
  const extToLang: Record<string, string> = {
    py: "Python",
    js: "JavaScript",
    ts: "TypeScript",
    java: "Java",
    cpp: "C++",
    c: "C",
    cs: "C#",
    go: "Go",
    rs: "Rust",
    rb: "Ruby",
    swift: "Swift",
    kt: "Kotlin",
    scala: "Scala",
    php: "PHP",
    dart: "Dart",
    rkt: "Racket",
    ex: "Elixir",
    erl: "Erlang",
  };

  // Add the new language
  langs.add(newLanguage);

  return Array.from(langs).map(
    (l) => extToLang[l] ?? l.charAt(0).toUpperCase() + l.slice(1)
  );
}

// Render the per-problem README.md.
export function renderProblemReadme(
  _dir: string,
  s: NormalizedSubmission,
  existingFiles?: string[] | null
): string {
  const solutions = mergeSolutionList(existingFiles ?? null, s.language);
  const difficultyBadge = getDifficultyBadge(s.difficulty);

  return `# ${escapeMd(s.title)}

${difficultyBadge}

| Property | Value |
|----------|-------|
| **Platform** | ${escapeMd(s.platform)} |
| **Difficulty** | ${escapeMd(s.difficulty)} |
| **Category** | ${escapeMd(s.category)} |
| **Tags** | ${s.tags.map(escapeMd).join(", ") || "—"} |
| **Problem Link** | [View Problem](${problemUrl(s)}) |

## Solutions

${solutions.map((lang, i) => `${i + 1}. ${escapeMd(lang)}`).join("\n")}

---

*Auto-generated by [Codexa](https://github.com/codexa) — your competitive programming companion.*
`;
}

// Get a markdown difficulty badge.
function getDifficultyBadge(difficulty: string): string {
  const colors: Record<string, string> = {
    Easy: "brightgreen",
    Medium: "orange",
    Hard: "red",
    Unknown: "lightgrey",
  };
  const color = colors[difficulty] ?? "lightgrey";
  return `![Difficulty](https://img.shields.io/badge/Difficulty-${encodeURIComponent(difficulty)}-${color})`;
}

// Render the root repository README.md.
export function renderRootReadme(analytics: AnalyticsSnapshot): string {
  const { total, byPlatform, byDifficulty, byLanguage, streak } = analytics;

  // Build platform stats table
  const platformRows = Object.entries(byPlatform)
    .sort(([, a], [, b]) => b - a)
    .map(([p, c]) => `| ${escapeMd(p)} | ${c} |`)
    .join("\n");

  // Build difficulty stats
  const difficultyRows = Object.entries(byDifficulty)
    .sort(([, a], [, b]) => b - a)
    .map(([d, c]) => `| ${escapeMd(d)} | ${c} |`)
    .join("\n");

  // Build language stats
  const languageRows = Object.entries(byLanguage)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 10)
    .map(([l, c]) => `| ${escapeMd(l)} | ${c} |`)
    .join("\n");

  // Recent submissions
  const recentRows = analytics.recentSubmissions
    .slice(0, 10)
    .map(
      (s) =>
        `| ${escapeMd(s.title)} | ${escapeMd(s.platform)} | ${escapeMd(s.difficulty)} | ${escapeMd(s.language)} |`
    )
    .join("\n");

  return `# 🏆 Competitive Programming Solutions

![Total Solved](https://img.shields.io/badge/Total%20Solved-${total}-blue)
![Current Streak](https://img.shields.io/badge/Current%20Streak-${streak.current}%20days-brightgreen)
![Longest Streak](https://img.shields.io/badge/Longest%20Streak-${streak.longest}%20days-orange)

> Auto-synced by **Codexa** — a browser extension that turns competitive programming submissions into a self-maintaining GitHub repository.

## 📊 Statistics

### By Platform

| Platform | Solved |
|----------|--------|
${platformRows || "| — | 0 |"}

### By Difficulty

| Difficulty | Count |
|------------|-------|
${difficultyRows || "| — | 0 |"}

### By Language

| Language | Count |
|----------|-------|
${languageRows || "| — | 0 |"}

## 📈 Recent Submissions

| Problem | Platform | Difficulty | Language |
|---------|----------|------------|----------|
${recentRows || "| — | — | — | — |"}

---

*Generated by [Codexa](https://github.com/codexa) • Updated ${new Date().toISOString().split("T")[0]}*
`;
}

// Generate a commit message for a submission.
export function commitMessage(s: NormalizedSubmission): string {
  const title = s.title.slice(0, 50);
  return `Add ${s.difficulty} ${title} (${s.language}) [${s.platform}]`;
}
